service: shedule-event

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  profile: ${env:AWS_PROFILE}
  
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      autoscaler:
        path: ./

  iam:
    role:
      name: shedule-event-scale
      statements:
      - Effect: 'Allow'
        Action: 
          - 'application-autoscaling:*'
          - 'autoscaling:UpdateAutoScalingGroup'
          - 'events:DeleteRule'
          - 'lambda:RemovePermission'
          - 'events:ListTargetsByRule'
          - 'events:DeleteEventBus'
          - 'events:DeleteConnection'
          - 'events:RemovePermission'
          - 'events:RemoveTargets'
          - 'events:DeleteArchive'          
        Resource: '*'
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole

custom:
  dotenv:
    path: ./.env.dev
    exclude:
      - AWS_PROFILE


functions:
  autoscale:
    image: 
      name: autoscaler
      command:
        - main.lambda_handler
