service: test-shedule-event

provider:
  name: aws
  region: us-east-1
  profile: electromech
  iam:
    role:
      name: test-shedule-event
      statements:
      - Effect: 'Allow'
        Action: 
          - 'lambda:AddPermission'
          - 'lambda:InvokeFunction'
        Resource: '*'
      managedPolicies:
      - 'arn:aws:iam::aws:policy/CloudWatchEventsFullAccess'

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./

functions:
  auto-shedule:
    image: 
      name: appimage
      command:
        - exam_shedule.generate_cloud_watch_rules
    environment:
      AUTOSCALE_LAMBDA_ARN: arn:aws:lambda:us-east-1:303373580614:function:test-shedule-event-dev-auto-shedule
