service: shedule-event
useDotenv: true


plugins:
  - serverless-dotenv-plugin

# variablesResolutionMode: 20210326

provider:
  name: aws
  region:  ${env:ENV_AWS_REGION}
  profile: ${env:ENV_AWS_PROFILE}
  iam:
    role:
      name: shedule-event-rules
      statements:
      - Effect: 'Allow'
        Action: 
          - 'lambda:AddPermission'
          - 'lambda:InvokeFunction'
          - 's3:GetObject'
        Resource: '*'
      managedPolicies:
      - 'arn:aws:iam::aws:policy/CloudWatchEventsFullAccess'

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      eventsheduler:
        path: ./

custom:
  dotenv:
    path: ./.env.dev
    exclude:
      - ENV_AWS_PROFILE

functions:
  rulesgen:
    image: 
      name: eventsheduler
      command:
        - exam_shedule.multi_sevice_shedule_rule
    events:
      - s3:
          bucket: ${env:BUCKET_NAME} # your bucket name
          event: s3:ObjectCreated:*
          rules:
            - suffix: ${env:BUCKET_FILE}
          existing: true
    environment:
      AUTOSCALE_LAMBDA_ARN: ${env:AUTOSCALE_LAMBDA_ARN}
      BUCKET_NAME: ${env:BUCKET_NAME} # your bucket name
      BUCKET_FILE: ${env:BUCKET_FILE} # your bucket filename
